#!/usr/bin/env python3
"""Bundle objects/*.py into the single-file orcad.py Hub artifact.

Each objects/<name>.py must define exactly SPEC + generate (no imports —
the Hub artifact is one self-contained file). This script AST-renames them
to <name>_SPEC / <name>_generate, smoke-tests codegen (defaults -> valid
python), and assembles PRIMITIVES + the generate_primitive_code dispatcher.

Usage:
    python3 packaging/bundle.py --write   # regenerate orcad.py region
    python3 packaging/bundle.py --check   # exit 1 when out of sync (tests)
"""
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OBJDIR = ROOT / "objects"
TARGET = ROOT / "orcad.py"
BEGIN = "# BEGIN BUNDLED OBJECTS"
END = "# END BUNDLED OBJECTS"


def _load_module(path):
    src = path.read_text(encoding="utf-8")
    tree = ast.parse(src, filename=str(path))
    names = set()
    for node in tree.body:
        if isinstance(node, ast.Expr):
            continue  # docstring / comments
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for target in targets:
                if not isinstance(target, ast.Name):
                    raise ValueError(f"{path}: complex top-level assignment")
                names.add(target.id)
        else:
            raise ValueError(f"{path}: unexpected top-level {type(node).__name__}")
    if names != {"SPEC", "generate"}:
        raise ValueError(f"{path}: must define exactly SPEC + generate, got {sorted(names)}")
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            raise ValueError(f"{path}: imports not allowed (single-file bundling)")
    stem = path.stem

    class _Renamer(ast.NodeTransformer):
        def visit_FunctionDef(self, node):
            if node.name == "generate":
                node.name = f"{stem}_generate"
            self.generic_visit(node)
            return node

        def visit_Name(self, node):
            if node.id == "SPEC":
                node.id = f"{stem}_SPEC"
            elif node.id == "generate":
                node.id = f"{stem}_generate"
            return node

    tree = _Renamer().visit(tree)
    # smoke-test: defaults through generate() must yield valid python
    namespace = {}
    exec(compile(tree, str(path), "exec"), {"__name__": f"objects.{stem}"}, namespace)
    spec = namespace[f"{stem}_SPEC"]
    assert spec.get("label") and isinstance(spec.get("params"), list), f"{path}: bad SPEC"
    for param in spec["params"]:
        assert {"key", "default"} <= set(param), f"{path}: bad param {param!r}"
    defaults = {p["key"]: p["default"] for p in spec["params"]}
    code = namespace[f"{stem}_generate"](defaults)
    ast.parse(code)
    return ast.unparse(tree)


def build_region():
    parts = []
    names = []
    for path in sorted(OBJDIR.glob("*.py")):
        if path.name.startswith("_") or path.name == "__init__.py":
            continue
        parts.append(_load_module(path))
        names.append(path.stem)
    if not names:
        raise ValueError("no object modules found in objects/")
    body = "\n\n\n".join(parts)
    entries = ",\n".join(f'    "{n}": {n}_SPEC' for n in names)
    dispatch = ",\n".join(f'        "{n}": {n}_generate' for n in names)
    return (
        "# Generated by `python3 packaging/bundle.py --write`.\n"
        "# Do not edit here; edit objects/*.py instead.\n"
        + body
        + f"\n\n\nPRIMITIVES = {{\n{entries},\n}}\n"
        + "\n\ndef generate_primitive_code(primitive, params):\n"
        + '    """Return build123d algebra-mode code string assigning `result`."""\n'
        + "    c = validate_primitive_params(primitive, params)\n"
        + "    try:\n"
        + f"        fn = {{\n{dispatch},\n        }}[primitive]\n"
        + "    except KeyError:\n"
        + '        raise ValueError(f"unknown object {primitive!r}")\n'
        + "    return fn(c)\n"
    )


def _split_target():
    lines = TARGET.read_text(encoding="utf-8").splitlines(keepends=True)
    begin = next(i for i, line in enumerate(lines) if line.rstrip("\n") == BEGIN)
    end = next(i for i, line in enumerate(lines) if line.rstrip("\n") == END)
    if not begin < end:
        raise ValueError("markers out of order")
    return lines, begin, end


def check():
    lines, begin, end = _split_target()
    return "".join(lines[begin + 1:end]) == build_region() + "\n"


def write():
    lines, begin, end = _split_target()
    text = "".join(lines[:begin + 1]) + build_region() + "\n" + "".join(lines[end:])
    TARGET.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    if "--write" in sys.argv:
        write()
        print("bundled objects into orcad.py")
    elif "--check" in sys.argv:
        sys.exit(0 if check() else 1)
    else:
        sys.exit("usage: bundle.py --write | --check")
